[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aggregator = "2De6Tg3Snwste9Bv73YJ9xLC12whrPnisdXBmTMqUv4j"

[programs.localnet]
aggregator = "2De6Tg3Snwste9Bv73YJ9xLC12whrPnisdXBmTMqUv4j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=5cc0897b-9a7c-44a9-bf01-7fbe84eb82c2"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
