[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aggregator = "7XEqP1W4vwMtPfkkgs97RnQSeksJHT1jSFuJvg3zm2Hs"

[programs.localnet]
aggregator = "7XEqP1W4vwMtPfkkgs97RnQSeksJHT1jSFuJvg3zm2Hs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
