[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aggregator = "9L6nUupwLAwSGPGQPmbGwGAd7S27nauTBCep22XF3RCT"

[programs.devnet]
aggregator = "9L6nUupwLAwSGPGQPmbGwGAd7S27nauTBCep22XF3RCT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
