[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aggregator = "7XEqP1W4vwMtPfkkgs97RnQSeksJHT1jSFuJvg3zm2Hs"

[programs.localnet]
aggregator = "7XEqP1W4vwMtPfkkgs97RnQSeksJHT1jSFuJvg3zm2Hs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha tests/**/*.test.ts"
